### ISSUE TITLE
Compatibility issues with adrenaline

### ISSUE THREAD

**Issue by mathieulh** [SKGleba/0syscall6#2]
I haven't had quite the chance to look in details so I do not know if either 0syscall6 or renga itself causes this issue, but when renga and the renga version of the 0syscall6 plugin are activated (I am using it with the 3.73 kprx_auth_sm if that changes anything), adrenaline crashes whenever I try to run it, if I disable both renga and 0syscall6 plugins, adrenaline runs just fine.

**Comment by Jgr9** [comment]
I know I shouldn't, but just tagging along with this.  Before I remembered to make sure 0syscall6 was disabled on 3.60 after installing the first iTLS 3.0 before the fix since it's not needed anymore, I was coming back to my Vita multiple times with it having (crashed?) rebooted on its own while in standby / screen off, and it saying that it wasn't shut down properly (with no error code).  Haven't seen it happen today after making sure 0syscall6 was disabled, though.

**Comment by Altheon1994** [comment]
Unit: PS Vita 1000 (3G Model)
Firmware: 3.60 Henkaku Enso
Possible Issue: Random shutdowns occur even on sleep mode. Unsure if this plugin is the root cause, will test further.
Comments: Could there be any plugin that's conflicting with 0syscall6? For the record, I did disable ref00d while using 0syscall6.

Some plugins active just to name a few:

0syscall6.skprx
PSVshell.skprx
ITLS.skprx (also suprx under *ALL) - This is the recently released 3.0 version
bicr.skprx
NoPowerLimits.skprx

Attempted resolution: disabled 0syscall6 and tried ref00d again. Some games show an error code and would go back to livearea but the random shutdowns doesn't happen. (will test further) 

Any game would start normally with 0syscall6 however. But again, the shutdowns do occur from time to time. (Still testing this as of now)

@Jgr9 - We're experiencing the same issue most probably. Sorry @SKGleba if we're riding on this issue here.

**Comment by Jgr9** [comment]
Well mine's still been in standby for a while, seemingly fine, since I disabled 0syscall6, which supposedly isn't needed for the most recent iTLS 3.0 fix on 3.60 anymore.  You should uninstall the now-outdated iTLS 3.0 through its installer and redownload and install the most updated/fixed 3.0? and of course disable 0syscall6... unless you needed that for something else?

**Comment by SKGleba** [comment]
Ok, there are two issues here:
- 0syscall6/psp2renga wakeup shutdown (related to the resume-bypass hook).
- 0syscall6/psp2renga compatibility issue (w adrenaline).
I will open them on psp2renga repo, ty for the observation.

**Comment by Altheon1994** [comment]
> Well mine's still been in standby for a while, seemingly fine, since I disabled 0syscall6, which supposedly isn't needed for the most recent iTLS 3.0 fix on 3.60 anymore.  You should uninstall the now-outdated iTLS 3.0 through its installer and redownload and install the most updated/fixed 3.0? and of course disable 0syscall6... unless you needed that for something else?

Yeah I do have the updated iTLS 3.0 but I'll need 0syscall6 in lieu of ref00d since it doesn't work anymore even with the updated keys. Not sure why, but that's gonna be a question for dots-TB.

**Comment by SKGleba** [comment]
Yeah its a renga issue, not 0syscall6.

**Comment by mathieulh** [comment]
I created the issue in psprenga https://github.com/SKGleba/psp2renga/issues/2
